### ISSUE TITLE
Official SPI library

### ISSUE THREAD

**Issue by anguskeatinge** [dreamcat4/Mcp4261#5]
All you need to do to get this working with the stock SPI library is add SPI.begin() to the instantiation of the object.

It would have saved me a bit of time and will probably save others time if you mention this in the README

**Comment by anguskeatinge** [comment]
Obviously you end up calling SPI.begin() multiple times if you have multiple pots. While not elegant, it doesn't break anything.

**Comment by mortensent** [comment]
I was wondering why the demo file wasn't outputting anything over SPI. Adding SPI.Begin() to setup worked.

Tested with an MCP4341 and Wiper0 and Wiper1 both work as expected. Hopefully getting the other 2 wipers working won't be too hard.

**Comment by dreamcat4** [comment]
Hi there. Thank you for raising the issue here.  If you guys want to put together a pull requesy, and have the other guy check it. Then I would be happy to merge any such PRs or documentation changes. Unfortunately I cannot test this myself while I'm not setup for working on any arduino hardware. Kind regards.

**Comment by dreamcat4** [comment]
closed by https://github.com/dreamcat4/Mcp4261/pull/7
